# Generated by Django 6.1.1 on 2026-09-30 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Reservation Day',
                'verbose_name_plural': 'Reservation Days',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='turns_app.reservationday', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-time'],
                'constraints': [models.UniqueConstraint(fields=('user', 'day', 'time'), name='unique_reservation_day_time')],
            },
        ),
    ]
